export default {
    entry: ["."],
    exclude: [
        'node_modules/**',
        'scripts/**',
        'dist/**',
        'vite.config.ts',
        'tailwind.config.js',
        'postcss.config.js',
        '**/*.d.ts',
        'src/utils/i18n.tsx'
    ],
    local: "zh",
    localPath: "./locales",
    langs: ["en-US"],
    keyPrefix: "",
    keygenStrategy: "md5",
    keyShowOrigin:false,
    i18nImport: "import i18nInstance from '@/utils/i18n';",
    i18nObject: "i18nInstance",
    i18nMethod: "t",
    translate: {},
    ignoreText: "i18n-disable",
    ignoreMethods: ["console.log"],
    ignoreAttributes: ["style", "class", "script", "id"],
};
