apiVersion: v1
kind: Secret
metadata:
  name: karmada-cert-secret
  namespace: karmada-system
type: Opaque
data:
  ca.crt: |
    {{ca_crt}}
  ca.key: |
    {{ca_key}}
  karmada.crt: |
    {{client_crt}}
  karmada.key: |
    {{client_key}}
  apiserver.crt: |
    {{apiserver_crt}}
  apiserver.key: |
    {{apiserver_key}}
  front-proxy-ca.crt: |
    {{front_proxy_ca_crt}}
  front-proxy-client.crt: |
    {{front_proxy_client_crt}}
  front-proxy-client.key: |
    {{front_proxy_client_key}}
  etcd-ca.crt: |
    {{etcd_ca_crt}}
  etcd-server.crt: |
    {{etcd_server_crt}}
  etcd-server.key: |
    {{etcd_server_key}}
  etcd-client.crt: |
    {{etcd_client_crt}}
  etcd-client.key: |
    {{etcd_client_key}}
